version: "3.9"
services:
  redis:
    image: redis:alpine
    networks:
      - backend
    ports:
      - "6379"
  django_app:
    build:
      context: .
      target: django_app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    expose:
      - "8000"
    networks:
      - backend
    ports:
      - "8000:8000"
    volumes:
      - app_code:/app
      - sqlite_db:/var/sqlite_db
  celery:
    build:
      context: .
      target: celery
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    networks:
      - backend
    volumes:
      - app_code:/app
      - sqlite_db:/var/sqlite_db
networks:
    backend:
        driver: bridge
volumes:
  app_code:
  sqlite_db:
