version: "3.9"
services:
  redis:
    image: redis:alpine
    networks:
      - backend
    ports:
      - "6379"
  django_app:
    build:
      context: .
      target: django_app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    expose:
      - "8000"
    networks:
      - backend
    ports:
      - "8000:8000"
  celery:
    build:
      context: .
      target: celery
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    networks:
      - backend
networks:
    backend:
        driver: bridge
